version: '3'
services:
  # ---------------------------
  # 前台
  # ---------------------------
  sz-education-web:
    image: registry.cn-hangzhou.aliyuncs.com/sz-education/sz-education-web:latest
    volumes:
      # 挂载nginx的配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: web-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "80:80"
    networks:
      - net

  # ---------------------------
  # 后台
  # ---------------------------
  sz-education-ui:
    image: registry.cn-hangzhou.aliyuncs.com/sz-education/sz-education-ui:latest
    volumes:
      # 挂载nginx的配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: ui-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "81:80"
    networks:
      - net

#  # ---------------------------
#  # example
#  # ---------------------------
#  sz-education-web-Spencer:
#    image: registry.cn-hangzhou.aliyuncs.com/sz-education/exam-web-example:latest
#    volumes:
#      # 挂载nginx的配置文件
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    container_name: web-service-example
#    env_file: docker-compose.env  # 从文件中获取配置
#    restart: always
#    ports:
#      - "88:80"
#    networks:
#      - net

networks:
  net:
    driver: bridge

volumes:
  data:
    driver: local