# 生产环境的配置，采用git方式
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shimmerjordan/sz-education/tree/master/config-service   # 配置git仓库的地址
          username:                                                 # git仓库的账号
          password:                                                 # git仓库的密码
