name: Delete super-linter.log

on:
  schedule:
    - cron:  '0 0 1/4 * *'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        

      ################################
      # delete linter log every days   #
      ################################
      - name: Lint Code Base
        run: |
          rm -f super-linter.log
     
    # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "shimmerjordan"
          git config --global user.email "shimmerjordan@foxmail.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update Lint Code Base logs' || echo
          git push origin HEAD:master --force
